### ISSUE TITLE
can you share your pretrained model?

### ISSUE THREAD

**Issue by luoolu** [DensoITLab/HCFormer#1]
use pretraiend model to test

**Comment by perrying** [comment]
The pretrained model (HCFormer+ with Swin-L backbone trained on COCO) can be downloaded [here](https://d-itlab.s3.ap-northeast-1.amazonaws.com/hcformer/HCFormer%2B-SwinL-COCO-200epoch.pth).
We updated `GETTING_STARTED.md`.
If you would like to use other architectures, please train from your environment.
